name: Build Gateway bootloaders
run-name: Build Gateway bootloaders

on:
  push:
    branches: [mono-development]
    tags: ['*']

jobs:

  trigger:

    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Trigger build-bootloaders..
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository_owner }}/workflows/dispatches \
            -d "{\"event_type\": \"trigger-build-bootloaders\", \"client_payload\": {\"from\": \"atf : ${{ github.sha }}\", \"atfRef\": \"${{ github.sha }}\"}}"
